[project]
name = "keyword-svc"
version = "0.1.0"
description = "Job offer keywords extractor with keyBERT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "keybert[sentence-transformers]>=0.9.0",
    "uvicorn>=0.34.2",
]
